### ISSUE TITLE
Is there another solution than compile Nginx with dynamic module ?

### ISSUE THREAD

**Issue by guizmaii** [leev/ngx_http_geoip2_module#28]
With dynamic module, if I understand well, I don't need to compile your code.
Just take the .so file, copy it in nginx modules folder and finally and the `load_module ...` directive in my nginx.conf.

Why should I compile your lib with a downloaded version of Nginx code ? I have the Nginx that come from repos.

**Comment by leev** [comment]
If you have a precompiled .so for the module, you don't need to download and compile nginx.  However if you need to compile the module, you need the nginx source.

**Comment by wingc-china** [comment]
From my own experience, the module I compiled locally did not work with the nginx binary installed from package. It could be caused by different compiler version, linked to different libs, or some specific compiler flag I missed? Who knows. I give up digging out cause and go ahead to re-compile the whole nginx myself as I have its source code in hand already.

**Comment by guizmaii** [comment]
@leev So, do you provide this .so file ?

**Comment by leev** [comment]
No.  You will need to compile it, or find someone else who has compiled it for your os/architecture.

**Comment by guizmaii** [comment]
Ok thanks for the answers.
